# Generated by Django 5.2.5 on 2025-08-27 20:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_message', models.TextField(default='Welcome to Riverway Company! How can I help you today?')),
                ('fallback_message', models.TextField(default="I'm sorry, I didn't understand. Let me connect you with a human agent.")),
                ('escalation_threshold', models.IntegerField(default=3, help_text='Number of unresolved attempts before escalation')),
                ('response_delay', models.FloatField(default=1.0, help_text='Simulated typing delay in seconds')),
                ('working_hours_message', models.TextField(default="We're currently outside business hours. Your message will be answered when we return.")),
                ('max_session_duration', models.IntegerField(default=3600, help_text='Maximum session duration in seconds')),
                ('enable_analytics', models.BooleanField(default=True)),
                ('enable_feedback', models.BooleanField(default=True)),
                ('enable_notifications', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Chatbot Settings',
                'verbose_name_plural': 'Chatbot Settings',
            },
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('keywords', models.TextField(help_text='Comma-separated keywords')),
                ('response_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='intent',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='response_time',
            field=models.FloatField(blank=True, help_text='Response time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='channel',
            field=models.CharField(choices=[('website', 'Website Widget'), ('whatsapp', 'WhatsApp'), ('messenger', 'Facebook Messenger'), ('telegram', 'Telegram'), ('email', 'Email')], default='website', max_length=20),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='escalated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('escalated', 'Escalated to Human'), ('resolved', 'Resolved'), ('abandoned', 'Abandoned')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='pricing_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='services',
            field=models.TextField(default='Construction materials and supplies', help_text='List of services offered'),
        ),
        migrations.AddField(
            model_name='faq',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords for matching'),
        ),
        migrations.AddField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('user', 'User Message'), ('bot', 'Bot Response'), ('system', 'System Message'), ('agent', 'Human Agent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(default='Riverway Company Limited', max_length=200),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('general', 'General Information'), ('services', 'Services'), ('pricing', 'Pricing'), ('location', 'Location & Hours'), ('support', 'Support'), ('products', 'Products'), ('orders', 'Orders & Shipping')], default='general', max_length=100),
        ),
        migrations.CreateModel(
            name='ChatAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_sessions', models.IntegerField(default=0)),
                ('resolved_queries', models.IntegerField(default=0)),
                ('escalated_queries', models.IntegerField(default=0)),
                ('average_response_time', models.FloatField(default=0.0)),
                ('average_session_duration', models.FloatField(default=0.0)),
                ('user_satisfaction_score', models.FloatField(default=0.0)),
                ('channel_website', models.IntegerField(default=0)),
                ('channel_whatsapp', models.IntegerField(default=0)),
                ('channel_messenger', models.IntegerField(default=0)),
                ('most_common_intent', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Chat Analytics',
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')])),
                ('feedback_text', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('was_helpful', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='EscalationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('escalation_time', models.DateTimeField(auto_now_add=True)),
                ('response_time', models.DateTimeField(blank=True, null=True)),
                ('resolution_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_escalations', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('order_status', 'Order Status Update'), ('promotional', 'Promotional'), ('reminder', 'Reminder'), ('escalation', 'Escalation Alert')], max_length=30)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
